### ISSUE TITLE
Fatal Exception: java.lang.UnsatisfiedLinkError No implementation found for java.lang.String com.instabug.library.network.service.synclogs.SyncLogKeyProvider.getNativeMatchingEmailPrefix()

### ISSUE THREAD

**Issue by RajaReddyP** [Instabug/Instabug-Android#317] opened 2020-06-20 01:21 UTC
This issue happening in two places 

```
1. Fatal Exception: java.lang.UnsatisfiedLinkError
No implementation found for java.lang.String com.instabug.library.network.service.synclogs.SyncLogKeyProvider.getNativeMatchingEmailPrefix() (tried Java_com_instabug_library_network_service_synclogs_SyncLogKeyProvider_getNativeMatchingEmailPrefix and Java_com_instabug_library_network_service_synclogs_SyncLogKeyProvider_getNativeMatchingEmailPrefix__)
```

```
2. Caused by java.lang.UnsatisfiedLinkError
No implementation found for java.lang.String com.instabug.library.network.authorization.NetworkOfficer.getClientId() (tried Java_com_instabug_library_network_authorization_NetworkOfficer_getClientId and Java_com_instabug_library_network_authorization_NetworkOfficer_getClientId__)

Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:354)
```
### Steps to Reproduce the Problem
No specific steps to reproduce this issue. 

### Expected Behavior
The application should not crash.

### Actual Behavior
Application crashing.

### Instabug integration code
  ```
Instabug.Builder(mApplication, instabugToken)
                .setInvocationEvents(InstabugInvocationEvent.SHAKE)
                .build()
```

### SDK Version
9.1.5

### Android Version
Android 9

### Device Model
AOSP on IA Emulator

**Comment by tgvoskuilen** [comment] 2020-06-20 14:59
I can confirm I'm seeing both these errors too with 9.1.4

**Comment by RajaReddyP** [comment] 2020-06-20 16:04
@tgvoskuilen Can you please confirm will you able to fix these issues? else suggest code changes in my app.

**Comment by tgvoskuilen** [comment] 2020-06-20 16:27
I have not found a fix - the errors are still happening in production. The suggestion on the other tickets to do a clean build did not fix it for me.

https://github.com/Instabug/Instabug-Android/issues/308
https://github.com/Instabug/Instabug-Android/issues/305

**Comment by tgvoskuilen** [comment] 2020-06-20 16:29
Also, I reported these to Instabug back in April 2020...

**Comment by mzelzoghbi** [comment] 2020-06-20 16:39
These errors should be fixed on 9.1.5 🤔, if not can we know if are you using the new app bundles while shipping your app to the store or you are normally exporting an .apk file?

**Comment by RajaReddyP** [comment] 2020-06-21 01:12
@mzelzoghbi - I am using exporting .apk file to store. 
```
implementation "com.instabug.library:instabug:9.1.5"
implementation "com.instabug.library:instabug-with-okhttp-interceptor:9.1.4"
```

**Comment by mzelzoghbi** [comment] 2020-06-21 08:23
@RajaReddyP can you make sure that both interceptor and instabug have the same versions 9.1.5 and let us know if this fixed the issue

**Comment by romainpiel** [comment] 2020-06-29 13:07
Hi, I'm seeing the same issue on instabug 9.1.5:
```
Fatal Exception: java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String com.instabug.library.network.service.synclogs.SyncLogKeyProvider.getNativeMatchingEmailPrefix() (tried Java_com_instabug_library_network_service_synclogs_SyncLogKeyProvider_getNativeMatchingEmailPrefix and Java_com_instabug_library_network_service_synclogs_SyncLogKeyProvider_getNativeMatchingEmailPrefix__)
       at com.instabug.library.network.service.synclogs.SyncLogKeyProvider.getNativeMatchingEmailPrefix(SyncLogKeyProvider.java)
       at com.instabug.library.network.service.synclogs.SyncLogKeyProvider.f(SyncLogKeyProvider.java:1)
       at com.instabug.library.network.service.synclogs.b.c(b.java:4)
       at com.instabug.library.network.service.synclogs.b.a(b.java:24)
       at com.instabug.library.network.service.synclogs.b.d(b.java:4)
       at com.instabug.library.network.service.synclogs.b.a(b.java:7)
       at com.instabug.library.c.A(c.java:6)
       at com.instabug.library.c.m(c.java:1)
       at com.instabug.library.c$n.run(c.java:1)
       at com.instabug.library.internal.orchestrator.ActionsOrchestrator.runAction(ActionsOrchestrator.java:3)
       at com.instabug.library.internal.orchestrator.ActionsOrchestrator.access$100(ActionsOrchestrator.java:1)
       at com.instabug.library.internal.orchestrator.ActionsOrchestrator$a.run(ActionsOrchestrator.java:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at com.instabug.library.util.threading.b$a.run(b.java:8)
       at java.lang.Thread.run(Thread.java:818)
```

I have only included this dependency: `implementation "com.instabug.library:instabug:9.1.5"`

**Comment by mzelzoghbi** [comment] 2020-06-29 13:19
@romainpiel Is this reproducible on your side? If Yes can you provide us with the reprosteps and if No can you help us by providing some more information to fix this? we will need to know your **gradle-wrapper** version, **build tool & android studio** versions, **compile/target SDK** versions, **NDK** version, no. of occurrences/device-models/os-levels and also how do you share your app, are you using **apk** or **app bundles** ? 

Thank You 🙏

**Comment by romainpiel** [comment] 2020-06-29 13:36
Unfortunately not reproducible on our side, I only got that from Crashlytics.

gradle-wrapper: 6.1.1
build tools: 29.0.2
android studio: 4.0
compile SDK: 29
target SDK: 28
no NDK
occurrences: only once for now (Motorola One Vision 5.1) but we just started the rollout with a version that adds Instabug
we share our app via app bundles

**Comment by mzelzoghbi** [comment] 2020-07-12 23:55
Hi @romainpiel  ,
Please accept our apologies for the inconvenience we may have caused. We have been trying to reproduce the issue but unfortunately, we didn't reach anything. 
The only assumption is that your application may be shared via **.apk** from device to the other with different **CPU architectures** (Using sharing apps like shareit,,, etc), which led in missing `.so` libs that we use and depend on it to work.

To fix this you will need to avoid splitting **ABIs** while releasing **aab** by adding this snippet to your app's **build.gradle** file 
```
android {
     .....
    bundle {
        abi {
            enableSplit = false
        }
    }
}
```

Please try this and let us know if the issue still persists.

Thank You!

**Comment by SudoPlz** [comment] 2020-07-27 13:18
can anyone confirm that `enableSplit = false` fixes the issue?

We're seeing that in production as well!

Thanks

**Comment by RajaReddyP** [comment] 2020-09-01 15:32
Hi @mzelzoghbi ,

We are seeing this issue happening in our production. Can you please let us know if there is any fix available.
We shipped our app to the PlayStore using new app bundles.

A crash report from Firebase(There are a total of 12 events affecting one user)
Device: Nexus 5X, API 8.1.0

**Stack trace**
Caused by java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String com.instabug.library.network.authorization.NetworkOfficer.getClientId() (tried Java_com_instabug_library_network_authorization_NetworkOfficer_getClientId and Java_com_instabug_library_network_authorization_NetworkOfficer_getClientId__)
       at com.instabug.library.network.authorization.NetworkOfficer.getClientId(NetworkOfficer.java)
       at com.instabug.library.network.authorization.NetworkOfficer.a(NetworkOfficer.java:9)
       at com.instabug.library.network.NetworkManager.buildConnection(NetworkManager.java:10)
       at com.instabug.library.network.NetworkManager.connectWithNormalType(NetworkManager.java:2)
       at com.instabug.library.network.NetworkManager.access$100(NetworkManager.java:1)
       at com.instabug.library.network.NetworkManager$a.subscribe(NetworkManager.java:20)
       at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
       at io.reactivex.Observable.subscribe(Observable.java:12284)
       at com.instabug.bug.view.actionList.service.a.a(a.java:12)
       at com.instabug.bug.view.actionList.service.ReportCategoriesService.a(ReportCategoriesService.java:5)
       at com.instabug.bug.view.actionList.service.ReportCategoriesService.runBackgroundTask(ReportCategoriesService.java:1)
       at androidx.core.app.InstabugBackgroundService.onHandleWork(InstabugBackgroundService.java:6)
       at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:392)
       at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
       at android.os.AsyncTask$2.call(AsyncTask.java:333)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

**Instabug setup in our app**
implementation "com.instabug.library:instabug:9.1.5"
implementation "com.instabug.library:instabug-with-okhttp-interceptor:9.1.5"

**Comment by mzelzoghbi** [comment] 2020-09-01 15:35
Hello @RajaReddyP 
We have a **SNAPSHOT** that should fix the issue, Can you please try it and tell us if it fixed the issue for you?
``` 
implementation 'com.instabug.library:instabug:9.1.6.11-SNAPSHOT'
```
you will need to add these lines to your app **build.gradle** before your dependencies
```
repositories {
    ....
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```
This **SNAPSHOT** is completely safe to use and has no debug code at all.

Thank You 😃

**Comment by RajaReddyP** [comment] 2020-09-02 00:53
@mzelzoghbi Thanks for sharing the snapshot. The problem is we are seeing issue only in production and not able to reproduce while debugging. Can I know when the stable release will be available?

**Comment by IgorMaineti** [comment] 2020-09-04 14:49
@mzelzoghbi I'm waiting for the stable release as well, do you know when the next stable release will be available?

**Comment by mzelzoghbi** [comment] 2020-09-04 17:19
@RajaReddyP @IgorMaineti Our next release will be in a week from now. However i highly recommend using the snapshot it only has the fix without any debug code.

**Comment by dpnolte** [comment] 2020-09-09 06:05
@mzelzoghbi We're also seeing this crash report coming in. I tried to use snapshot `com.instabug.library:instabug:9.1.6.11-SNAPSHOT` but gradle reports _Failed to resolve: com.instabug.library:instabug-apm:9.1.6.11-SNAPSHOT_. 
The snapshot version, `com.instabug.library:instabug:9.1.6.12-SNAPSHOT`, is resolving though. Does this snapshot also include the fix? In any case, I hope the fix can be released soon 🙇

**Comment by mzelzoghbi** [comment] 2020-09-09 09:45
@dpnolte Can you try to refresh the dependencies using and let me know if it fixed your issue or not?
```
./gradlew --refresh-dependencies``` 

And for our public release, We are releasing our public build early next week.

**Comment by SudoPlz** [comment] 2020-09-09 14:20
@mzelzoghbi 9.1.7 is out, is that included on that version, or do we have to wait for 9.1.8? And if so when will 9.1.8 be out?

Thanks

**Comment by AliAbdelfattah** [comment] 2020-09-10 04:05
@SudoPlz could you clarify what you mean by 9.1.7 is out? the latest Android release as of this point is 9.1.6.

**Comment by dpnolte** [comment] 2020-09-10 05:00
@mzelzoghbi  Unfortunately, `./gradlew --refresh-dependencies` didn't help. It still can't resolve `com.instabug.library:instabug-apm` with snapshot version `9.1.6.11-SNAPSHOT`.

**Comment by SudoPlz** [comment] 2020-09-10 13:45
@AliAbdelfattah I noticed 9.1.7 is available [in npm](https://www.npmjs.com/package/instabug-reactnative) https://p-5JFjjq.b1.n0.cdn.getcloudapp.com/items/Blu5eKvq/Image%202020-09-10%20at%204.44.59%20PM.png?v=3232198c70ef265bb6a2ec320474eb30

**Comment by mzelzoghbi** [comment] 2020-09-11 17:25
This issue has been fixed on our latest native SDK build `9.1.7`, Please try it out and feel free to reach out if you faced any further issues.

Thank You 😊

**Closed by mzelzoghbi** 2020-09-11 17:25 UTC
Labels: pending-feedback

**Comment by Danlos** [comment] 2021-07-01 00:59
I'm getting this same error on 10.7.1.
`No implementation found for java.lang.String com.instabug.library.network.service.synclogs.SyncLogKeyProvider.getNativeMatchingEmailPrefix() (tried Java_com_instabug_library_network_service_synclogs_SyncLogKeyProvider_getNativeMatchingEmailPrefix and Java_com_instabug_library_network_service_synclogs_SyncLogKeyProvider_getNativeMatchingEmailPrefix__)
No implementation found for java.lang.String com.instabug.library.network.authorization.NetworkOfficer.getClientId() (tried Java_com_instabug_library_network_authorization_NetworkOfficer_getClientId and Java_com_instabug_library_network_authorization_NetworkOfficer_getClientId__)
No implementation found for java.lang.String com.instabug.library.network.authorization.NetworkOfficer.getClientId() (tried Java_com_instabug_library_network_authorization_NetworkOfficer_getClientId and Java_com_instabug_library_network_authorization_NetworkOfficer_getClientId__)
API Checker: Instabug API {Instabug.disableInternal} was called while the SDK is disabled. To enable it, please call Instabug.enable().
No implementation found for java.lang.String com.instabug.library.network.service.synclogs.SyncLogKeyProvider.getNativeMatchingEmailPrefix() (tried Java_com_instabug_library_network_service_synclogs_SyncLogKeyProvider_getNativeMatchingEmailPrefix and Java_com_instabug_library_network_service_synclogs_SyncLogKeyProvider_getNativeMatchingEmailPrefix__)
API Checker: Instabug API {Instabug.disable} was called while the SDK is disabled. To enable it, please call Instabug.enable().`

This is my implementation in my Application class:

` public void onCreate() {
        super.onCreate();
        new Instabug.Builder(this, BuildConfig.INSTABUG_TOKEN)
                .setTrackingUserStepsState(Feature.State.DISABLED)
                .setInvocationEvents(InstabugInvocationEvent.SHAKE)
                .build();
        Feature.State state;
        if (isAndroidEmulator(this)) {
            state = Feature.State.DISABLED;
        } else {
            state = Feature.State.ENABLED;
        }
        CrashReporting.setState(state);

        Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED);
        Instabug.setSessionProfilerState(Feature.State.DISABLED);
        Instabug.enable();
        .
        .
        .
        `

**Comment by vietcompro** [comment] 2022-05-05 02:30
Hi there,

Sorry if it's too much to ask for but it would be really helpful if Instabug could hint us how did you fix this issue? As our internal product is also facing this and we're kind of stuck at the moment. Really appreciate your help!

Thank you.

**Comment by IslamMohamady** [comment] 2022-05-08 08:14
Hi @vietcompro 
If you are releasing to play store in form of AAB, This could happen because of APK sharing between devices. So you should check if the native library is successfully loaded before calling any native method.
