### ISSUE TITLE
Crash caused by the Instabug library

### ISSUE THREAD

**Issue by mayhammf** [Instabug/Instabug-Android#362] opened 2021-02-08 05:33 UTC
We are receiving crashes with the following message:
```
Caused by android.system.GaiException
android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
... stack trace below
```
I've seen similar issue reported and closed with the update being the fix (which isn't the case sadly)

We're using the lastest [instabug-for-android](https://www.nuget.org/packages/instabug-for-android/) NuGet package for Xamarin.Android V9.1.9. I'm posting this issue here as the nuget package is not in GitHub and the issue is caused by the underlying Android library.

### Steps to Reproduce the Problem
App crashes in production. 

### Expected Behavior
Instabug library works seamlessly and must not cause any crashes.

### Actual Behavior
App crashes. (over 400 crashes in the last 7 days alone and about 1500 crash in the last 30 days)

### Instabug integration code
C# code below
```
new Instabug
	.Builder(context, instabugToken)
	.SetInvocationEvents(InstabugInvocationEvent.None)
	.Build();

Instabug.SetViewHierarchyState(Feature.State.Disabled);
Instabug.SetTrackingUserStepsState(Feature.State.Disabled);
Instabug.SetReproStepsState(Com.Instabug.Library.Visualusersteps.State.Disabled);

Instabug.SetColorTheme(InstabugColorTheme.InstabugColorThemeDark);
Instabug.SetWelcomeMessageState(WelcomeMessage.State.Disabled);

BugReporting.SetFloatingButtonEdge(InstabugFloatingButtonEdge.Right);
BugReporting.SetFloatingButtonOffset(120);

BugReporting.SetInvocationEvents(InstabugInvocationEvent.None);
BugReporting.SetShakingThreshold(500);
BugReporting.SetAttachmentTypesEnabled(true, false, false, false);
BugReporting.SetAutoScreenRecordingEnabled(false);
```

### SDK Version
instabug-for-android V9.1.9

### Android Version
Various versions. E.g: 11, 10, 9, 8
![image](https://user-images.githubusercontent.com/5937658/107178797-40bcd600-69d5-11eb-93b6-5ec23e179f10.png)

### Device Model
Various models. 
![image](https://user-images.githubusercontent.com/5937658/107178831-50d4b580-69d5-11eb-8e79-5f2e931687c7.png)

### Exception stack trace
```
Caused by android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
       at libcore.io.Linux.android_getaddrinfo(Linux.java)
       at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:74)
       at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:200)
       at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:74)
       at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
       at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
       at java.net.InetAddress.getAllByName(InetAddress.java:1152)
       at com.android.okhttp.Dns$1.lookup(Dns.java:41)
       at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:178)
       at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:144)
       at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:86)
       at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:192)
       at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:144)
       at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:106)
       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:400)
       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:333)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:483)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:135)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:266)
       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:219)
       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:30)
       at com.instabug.library.network.NetworkManager.connectWithNormalType(:75)
       at com.instabug.library.network.NetworkManager.access$100()
       at com.instabug.library.network.NetworkManager$a.subscribe(:96)
       at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(:10)
       at io.reactivex.Observable.subscribe(:14)
       at io.reactivex.internal.operators.observable.ObservableRetryPredicate$RepeatObserver.subscribeNext(:18)
       at io.reactivex.internal.operators.observable.ObservableRetryPredicate.subscribeActual(:21)
       at io.reactivex.Observable.subscribe(:14)
       at io.reactivex.internal.operators.observable.ObservableIgnoreElementsCompletable.subscribeActual(:7)
       at io.reactivex.Completable.subscribe(:14)
       at io.reactivex.internal.operators.completable.CompletablePeek.subscribeActual(:7)
       at io.reactivex.Completable.subscribe(:14)
       at io.reactivex.internal.operators.completable.CompletableAndThenCompletable.subscribeActual(:9)
       at io.reactivex.Completable.subscribe(:14)
       at io.reactivex.internal.operators.completable.CompletableAndThenCompletable.subscribeActual(:9)
       at io.reactivex.Completable.subscribe(:14)
       at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(:2)
       at io.reactivex.Scheduler$DisposeTask.run(:9)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run(:13)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call()
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```

### Observations
The crash seems to be network related, namely a DNS related issue where the a hostname is not getting resolved. 
This could be cause by the user's device being offline or due to the DNS not being reachable to the user. 

### Remarks
Instabug is included in the app for the for sole purpose of improving the user experience which makes any crash caused by it extra problematic, let alone causing around 1.5k crashes in the last month alone. 

Graph details the the crash and its impact on our users
![image](https://user-images.githubusercontent.com/5937658/107181524-49b0a600-69db-11eb-9c5c-d2a7fa8bb0a2.png)

I really hope this issue can be resolve as soon as possible and that you can understand our frustration.

And apologies for reporting this issue here but it is the only place to do so as the NuGet package is not on GitHub

**Comment by mayhammf** [comment] 2021-05-25 17:30
Issue still persist using the latest NuGet package for Android [](https://www.nuget.org/packages/instabug-for-android/)
attached stack trace. 
[Instabug - Android crash - stack trace.txt](https://github.com/Instabug/Instabug-Android/files/6541246/Instabug.-.Android.crash.-.stack.trace.txt)

**Comment by SudoPlz** [comment] 2021-06-15 08:55
We're seeing that too.

**Comment by IslamMohamady** [comment] 2021-08-10 13:52
Hi @mayhammf 
Can you upgrade the SDK version to 10.8 and try again? 
If the issue is resolved, Please make sure to close the issue

**Comment by mayhammf** [comment] 2021-08-10 19:09
@IslamMohamady crash is no longer occurring. Closing the issue.

**Closed** 2021-08-10 19:11 UTC
Labels: pending-feedback
