### ISSUE TITLE
NullPointerException while using feedback feature.

### ISSUE THREAD

**Issue by zfort-vitalii** [Instabug/Instabug-Android#64] opened 2017-10-05 15:23 UTC
Hi there, 

sometimes we got NPE during use your SDK. Perhaps you can help us to solve this issue.

`Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.---/com.instabug.library.InstabugFeedbackActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.instabug.library.bugreporting.model.Bug com.instabug.library.bugreporting.model.Bug.a(com.instabug.library.bugreporting.model.Bug$Type)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2434)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
       at android.app.ActivityThread.access$900(ActivityThread.java:157)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5551)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'com.instabug.library.bugreporting.model.Bug com.instabug.library.bugreporting.model.Bug.a(com.instabug.library.bugreporting.model.Bug$Type)' on a null object reference
       at com.instabug.library.InstabugFeedbackActivity.d(InstabugFeedbackActivity.java:363)
       at com.instabug.library.InstabugFeedbackActivity.a(InstabugFeedbackActivity.java:321)
       at com.instabug.library.InstabugFeedbackActivity.onCreate(InstabugFeedbackActivity.java:142)
       at android.app.Activity.performCreate(Activity.java:6272)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2387)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
       at android.app.ActivityThread.access$900(ActivityThread.java:157)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5551)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)`

Also i've got NPE when open Feedback and then press back button. Problem repeated quite seldom.  I've open feedback with this line of code 
`Instabug.invoke(InstabugInvocationMode.NEW_FEEDBACK);`
Don't know if the same. 

`Fatal Exception: java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
Caused by rx.exceptions.OnCompletedFailedException: Attempt to invoke virtual method 'com.instabug.library.bugreporting.model.Bug com.instabug.library.bugreporting.model.Bug.a(com.instabug.library.bugreporting.model.Bug$ViewHierarchyInspectionState)' on a null object reference
       at rx.observers.SafeSubscriber.onCompleted(SafeSubscriber.java:85)
       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.checkTerminated(OperatorObserveOn.java:281)
       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:216)
       at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'com.instabug.library.bugreporting.model.Bug com.instabug.library.bugreporting.model.Bug.a(com.instabug.library.bugreporting.model.Bug$ViewHierarchyInspectionState)' on a null object reference
       at com.instabug.library.f.a.a$1.onCompleted(ActivityViewInspector.java:144)
       at rx.observers.SafeSubscriber.onCompleted(SafeSubscriber.java:79)
       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.checkTerminated(OperatorObserveOn.java:281)
       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:216)
       at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)`

Version : 4.2.9

Hope this stacktrace help you.

**Comment by reemalashry1** [comment] 2017-10-09 11:27
Hey @zfort-vitalii 
We are currently investigating this, I'll get back to you 😊

**Comment by zfort-vitalii** [comment] 2017-10-09 11:56
Thank you!

**Comment by reemalashry1** [comment] 2017-10-10 23:22
Hey @zfort-vitalii 

The cause of the NPE you get with the feedback is fixed in 4.2.11.5-SNAPSHOT

To use the snapshot, please add the following lines to your app-level `build.gradle` file:

```dependencies {
 compile 'com.instabug.library:instabug:4.2.11.5-SNAPSHOT'
}
```


```repositories {
   maven {
       //  add this only if interested in getting SNAPSHOT releases
       url "https://oss.sonatype.org/content/repositories/snapshots"
   }
}```

**Comment by zfort-vitalii** [comment] 2017-10-11 09:43
Thanks! 
i can't reproduce it, hope uses too

**Comment by reemalashry1** [comment] 2017-10-11 11:19
@zfort-vitalii regarding the first NPE, we still can't reproduce it, do you mind sharing with me steps on how to reproduce it please? 😊

**Comment by zfort-vitalii** [comment] 2017-10-11 12:08
We got this issue within Crashlytics. That is why i don't know the steps. I'll let you know, if we have any crush with this again. 
Many thanks for fast response!

**Comment by reemalashry1** [comment] 2017-10-11 16:00
@zfort-vitalii Deal! You're welcome :)

**Closed** 2018-07-04 13:46 UTC
