### ISSUE TITLE
Overriding RxJavaPlugins error handler

### ISSUE THREAD

**Issue by jdamcd** [Instabug/Instabug-Android#163] opened 2019-01-16 10:52 UTC
Initialising the Instabug SDK overrides the `RxJavaPlugins` error handler, which changes the behaviour of RxJava usage in the host application. This was previously raised in https://github.com/Instabug/Instabug-Android/issues/126 and a fix was verified in `8.0.11.19-SNAPSHOT`. The issue persists in stable releases as of `8.0.15`.

### Steps to Reproduce the Problem

Initialise Instabug SDK via the builder. 

### Expected Behavior

No `RxJavaPlugins` error handler should be set, or it should not alter the error behaviour of the host application.

### Actual Behavior

Instabug registers an error handler, which causes fatal exceptions to be swallowed in certain cases (see sample project).

### Instabug integration code

See sample project.

### SDK Version

All `8.x.x` versions.

### Android Version

All versions.

### Device Model

All models.

### [Optional] Project That Reproduces the Issue

https://github.com/jdamcd/instabug-rx-issue

**Comment by mzelzoghbi** [comment] 2019-01-16 11:48
Unfortunately, we were unable to include the fix in the latest release, however, we will make sure to release it soon. I’ll update you once it is released. For now, we created a new snapshot **`8.0.15.1-SNAPSHOT`** that includes this RX fix plus the latest release fixes. It's completely safe to use and has no debug code at all.

**Comment by jdamcd** [comment] 2019-03-07 09:02
Hey @mzelzoghbi, we just re-tested with the latest version (8.1.1) and this is unresolved. Any update?

**Comment by mzelzoghbi** [comment] 2019-03-07 09:37
Hey @jdamcd , Unfortunately this was not included in the latest release, but it is planned to be included in the next release. For now we created a new snapshot **8.1.2.2-SNAPSHOT** that includes this RX fix plus the latest release fixes. It's completely safe to use and has no debug code at all.

**Comment by trevjonez** [comment] 2019-03-08 19:12
@mzelzoghbi still broken in 8.1.2.2-SNAPSHOT
![image](https://user-images.githubusercontent.com/5386503/54049288-5302b980-4199-11e9-9761-f7157b48b6cc.png)

simply add `RxJavaPlugins.lockdown()` before attempting to init instabug and it will explode when the call is made.

Instabug should not need to be aware of rx in the client at all.

and a workaround that doesn't feel as bad as using snapshots:
```
val errorHandler = RxJavaPlugins.getErrorHandler()
setupInstabug()
RxJavaPlugins.setErrorHandler(errorHandler)
RxJavaPlugins.lockdown()
```

**Comment by mzelzoghbi** [comment] 2019-03-09 11:45
Hi @trevjonez, We tried this and it worked without any issues. Can you please share with us a sample app?

**Comment by jdamcd** [comment] 2019-03-11 11:23
Oh cool, I didn't know about `RxJavaPlugins.lockdown()`!

We're using a similar workaround at the moment, but haven't tested out the latest snapshots, since we're not comfortable using a snapshot in production.

**Comment by mzelzoghbi** [comment] 2019-03-11 13:01
@jdamcd Snapshots are completely safe to use and have no debug code at all and we never override a snapshot once it is created.

**Comment by jdamcd** [comment] 2019-03-11 13:16
> we never override a snapshot once it is created

Even so, a snapshot _could_ be replaced, even accidentally. That's a big risk. We'd rather wait for the fix in a stable release.

**Comment by trevjonez** [comment] 2019-03-22 17:16
@mzelzoghbi if you just add that `RxJavaPlugins.lockdown()` to any app that uses instabug before instabug has been initialized you will reproduce the issue.

Also keep in mind there is probably a HUGE number of issues in production code that are effectively being try/catch/ignored by this issue. it is as though the instabug android sdk is doing exactly the sort of thing it should be trying to prevent.

**Comment by mzelzoghbi** [comment] 2019-05-06 10:46
Hi @jdamcd, I’m closing this issue because it has been fixed and released. Please reopen if you still encounter this issue with the latest version 8.3.0 Thank you! 😊

**Closed by mzelzoghbi** 2019-05-06 10:46 UTC

**Comment by jdamcd** [comment] 2019-05-07 11:24
Thanks for the update. Looking good to us! 🎉

**Comment by hugosvent** [comment] 2019-05-28 11:16
I encountered this on 8.4.0 on release variant,
weird that it works on debug mode but not release mode
