### ISSUE TITLE
Suspected "Thread starting during runtime shutdown" caused by Instabug 9.0 update

### ISSUE THREAD

**Issue by raymondctc** [Instabug/Instabug-Android#299] opened 2020-04-25 07:47 UTC
### Steps to Reproduce the Problem
Unfortunately we cannot reproduce the problem but we see some crash log like this on Crashlytics since 5th Mar, 2020. This was the time where we updated Instabug from 8.7.0 to 9.0.5.

![image](https://user-images.githubusercontent.com/13764117/80274089-83454880-870a-11ea-8b05-b6e5d64a97e1.png)

```
Fatal Exception: java.lang.InternalError: Thread starting during runtime shutdown
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start(Thread.java:733)
       at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:975)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1382)
       at com.amazon.device.ads.DtbThreadService.execute(DtbThreadService.java:52)
       at com.amazon.device.ads.DTBAdRequest.internalLoadAd(DTBAdRequest.java:451)
       at com.amazon.device.ads.DTBAdRequest.refreshAd(DTBAdRequest.java:492)
       at com.amazon.device.ads.DTBAdRequest.lambda$new$0(DTBAdRequest.java:50)
       at com.amazon.device.ads.DTBAdRequest.lambda$vNC3MnEso-tJf9ZKdjObyVMALQY(DTBAdRequest.java)
       at -$$Lambda$pu$vNC3MnEso-tJf9ZKdjObyVMALQY.run(-.java:2)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.os.HandlerThread.run(HandlerThread.java:65)
```

We suspect this crash is triggered by Instabug update is because
1. We don't have other changes/SDK updates that's affecting the above classes
2. Similar issue has happened before when we upgraded from Instabug 8.5.0 to 8.6.0 but it was resolved later in 8.7.0

```
Fatal Exception: java.lang.InternalError: Thread starting during runtime shutdown
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start + 733(Thread.java:733)
       at java.util.concurrent.ThreadPoolExecutor.addWorker + 975(ThreadPoolExecutor.java:975)
       at java.util.concurrent.ThreadPoolExecutor.execute + 1382(ThreadPoolExecutor.java:1382)
       at java.util.concurrent.Executors$DelegatedExecutorService.execute + 624(Executors.java:624)
       at com.google.android.exoplayer2.upstream.Loader$LoadTask.execute + 482(Loader.java:482)
       at com.google.android.exoplayer2.upstream.Loader$LoadTask.start + 343(Loader.java:343)
       at com.google.android.exoplayer2.upstream.Loader.startLoading + 236(Loader.java:236)
       at com.google.android.exoplayer2.source.ExtractorMediaPeriod.startLoading + 701(ExtractorMediaPeriod.java:701)
       at com.google.android.exoplayer2.source.ExtractorMediaPeriod.prepare + 203(ExtractorMediaPeriod.java:203)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.maybeUpdateLoadingPeriod + 1536(ExoPlayerImplInternal.java:1536)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.updatePeriods + 1399(ExoPlayerImplInternal.java:1399)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork + 513(ExoPlayerImplInternal.java:513)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage + 303(ExoPlayerImplInternal.java:303)
       at android.os.Handler.dispatchMessage + 102(Handler.java:102)
       at android.os.Looper.loop + 193(Looper.java:193)
       at android.os.HandlerThread.run + 65(HandlerThread.java:65)
```

Could you help to check?

### Instabug integration code
*Make sure to remove your app token.*

### SDK Version
9.1.0

### Android Version
All

### Device Model
Al

**Comment by Muhammadyoussef** [comment] 2020-04-28 11:47
Hi @raymondctc,

I noticed you are using another crash reporter. If this is the case, please disable the Instabug crash reporter to avoid any conflicts.

You can do so using the following API:
```
CrashReporting.setState(DISABLED) // after initializing Instabug
```

**Comment by raymondctc** [comment] 2020-05-18 01:18
Yes, we are using Crashlytics. I've just tried to set crash reporting disabled, but this crash is still happening in production in our latest release. 🤔

**Comment by mzelzoghbi** [comment] 2020-05-18 09:04
@raymondctc There is nothing in the stack trace relates to Instabug as both stack-traces you shared comes from different code paths, the first through amazon ads, and the other through exoplayer2.  I don't think it is caused by Instabug SDK. 
I am closing the issue, but please feel free to reopen if you feel that there is something that can we do from our side.

Thank You!

**Closed** 2020-05-18 09:05 UTC
