### ISSUE TITLE
java.lang.NullPointerException on BugReportingFragment.java:258

### ISSUE THREAD

**Issue by ghataa** [Instabug/Instabug-Android#128] opened 2018-10-01 12:46 UTC
Hi guys!

We just detected this crash in our live product:

`Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'com.instabug.library.model.State com.instabug.library.model.BaseReport.getState()' on a null object reference
       at com.instabug.bug.view.c.initViews(BugReportingFragment.java:258)
       at com.instabug.library.core.ui.BaseFragment.onCreateView(BaseFragment.java:38)
       at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
       at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
       at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3200)
       at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:195)
       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:597)
       at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
       at com.instabug.library.core.ui.BaseFragmentActivity.onStart(BaseFragmentActivity.java:50)
       at com.instabug.bug.view.BugReportingActivity.onStart(BugReportingActivity.java:123)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1249)
       at android.app.Activity.performStart(Activity.java:6897)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2684)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2782)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1521)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:163)
       at android.app.ActivityThread.main(ActivityThread.java:6228)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)`

### Steps to Reproduce the Problem
So far the only affected device is: Xiaomi Redmi 5A

### SDK Version
com.instabug.library:instabug:8.0.8

### Android Version
7

### Device Model
Xiaomi Redmi 5A

**Comment by Korazy** [comment] 2018-10-01 12:54
Hey @ghataa 

Thanks for reaching out, we will look into a fix for this and keep you updated.

**Comment by Korazy** [comment] 2018-10-02 22:04
Hey @ghataa 

We just had a few questions as we are unable to reproduce this issue.
1 - Is this issue consistent?
2 - Are there any particular steps you are aware of that leads to this crash occurring?
3 - Has this crash occurred several times?

**Comment by ghataa** [comment] 2018-10-03 10:00
Hi @Korazy 

1) Yes, but only on Xiaomi Redmi 5A so far

3) Yes

2) Nothing special I guess. It happens right after opening the app. Here is how I configured Instabug on Android:
`    private void initInstabug() {
        new Instabug.Builder(this, BuildConfig.INSTABUG_APP_ID)
                .setInvocationEvents(InstabugInvocationEvent.SHAKE, InstabugInvocationEvent.SCREENSHOT)
                .build();

        Instabug.setPrimaryColor(ContextCompat.getColor(this, R.color.colorSecondary));
        Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED);

        BugReporting.setShakingThreshold(300);
        BugReporting.setInvocationOptions(InvocationOption.EMAIL_FIELD_HIDDEN);
        BugReporting.setPromptOptionsEnabled(PromptOption.CHAT, PromptOption.BUG, PromptOption.FEEDBACK);
    }`

**Comment by bushmen** [comment] 2018-10-04 14:32
Hi @Korazy 

I have been experiencing the same issue in my Xamarin.Android application. The application crashes after clicking "Report a problem" on "How can we help you?" dialog. However I have noticed that exception is being thrown only from application deployed through Rider and it's working fine when download via hockeyApp (the hockey app build is build by TeamCity). I can provide more info if you need. Please let me know.

Regards,
Filip

**Comment by Korazy** [comment] 2018-10-07 10:51
Hey All,

Apologies for the delay on this. Would you be able to give this snapshot a go? It should have a fix for this: 8.0.10.3-SNAPSHOT

To be able to grab a snapshot, please add the following to your code as well:
repositories {
    maven {
        // TODO add this only if interested in getting SNAPSHOT releases
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}

**Comment by Korazy** [comment] 2018-10-15 12:15
Hey all,

Did this snapshot fix the issue for you?

**Comment by Korazy** [comment] 2018-10-22 09:22
Please feel free to reopen the issue should it occur again :)

**Closed** 2018-10-22 09:21 UTC

**Comment by vicobz** [comment] 2019-01-21 10:09
Hey ! Just got this crash on Samsung S8 with Instabug 8.0.11

**Comment by mzelzoghbi** [comment] 2019-01-21 10:12
Hey @vicobz 
Can you share with us the crash stacktrace?

**Comment by vicobz** [comment] 2019-01-21 10:46
Hey @mzelzoghbi,

Here is the stacktrace:

```java.lang.NullPointerException: Attempt to invoke virtual method 'com.instabug.library.model.State com.instabug.library.model.BaseReport.getState()' on a null object reference
	 at com.instabug.bug.e$1.run(LiveBugManager.java:160)
	 at java.lang.Thread.run(Thread.java:764)```

**Comment by vicobz** [comment] 2019-03-05 11:21
Hey @mzelzoghbi , any update on this?

**Comment by ajaysharma1990** [comment] 2019-03-20 03:46
Attempt to invoke virtual method 'java.util.Locale com.instabug.library.g.b.a(android.content.Context)' on a null object reference

**Comment by mzelzoghbi** [comment] 2019-03-20 10:52
@vicobz can you please try our latest version 8.1.2 it should fix this issue.

**Comment by mzelzoghbi** [comment] 2019-03-20 10:54
@ajaysharma1990 Can you please provide us with Instabug SDK Version, OS version, full stack trace, and repro steps if there are any?

**Comment by ajaysharma1990** [comment] 2019-03-20 11:13
hi @mzelzoghbi  I am using implementation 'com.instabug.library:instabug:4.2.11.5-SNAPSHOT'  library for instabug and 3-4 issue are getting every day.

**Comment by mzelzoghbi** [comment] 2019-03-20 11:18
@ajaysharma1990 Wow, This is a very old version. can you migrate to 8.1.2? it contains many bug fixes and also many new features.

**Comment by ajaysharma1990** [comment] 2019-03-20 11:21
@mzelzoghbi Thanks

**Comment by ajaysharma1990** [comment] 2019-03-20 11:25
@mzelzoghbi  Can you please help me for this issue also. Not allowed to start service Intent { cmp=com.WegileWildcard.transform905009/com.instabug.library.network.worker.uploader.InstabugSessionUploaderService }: app is in background uid UidRecord{10bdbc0 u0a147 TRNB idle procs:1 seq(0,0,0)}.

**Comment by mzelzoghbi** [comment] 2019-03-20 11:29
@ajaysharma1990 This is already fixed on our latest version

**Comment by ajaysharma1990** [comment] 2019-03-20 11:40
@mzelzoghbi Thank you so much.

**Comment by ajaysharma1990** [comment] 2019-03-25 04:58
hi @mzelzoghbi  i am getting this error with your latest dependency  8.1.2


Caused By : Unable to open the database file.
    	(unable to open database file (code 14): , while compiling: PRAGMA journal_mode)
    #################################################################
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1008)
        at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:712)
        at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:389)
        at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:363)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:252)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:203)
        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:518)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:209)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:181)
        at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:1152)
        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:1097)
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:828)
        at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:681)
        at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:319)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
        at com.instabug.library.internal.storage.cache.db.SQLiteDatabaseWrapper.open(SQLiteDatabaseWrapper.java:30)
        at com.instabug.library.internal.storage.cache.db.DatabaseManager.openDatabase(DatabaseManager.java:32)
        at com.instabug.library.internal.storage.cache.b.a(SessionDbHelper.java:33)
        at com.instabug.library.e.i(SessionManager.java:129)
        at com.instabug.library.e.h(SessionManager.java:108)
        at com.instabug.library.e.c(SessionManager.java:75)
        at com.instabug.library.a.a.uncaughtException(InstabugUncaughtExceptionHandler.java:30)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)

**Comment by mzelzoghbi** [comment] 2019-03-25 09:48
@ajaysharma1990 Thanks for reporting this. This is not the same crash in the thread, so please can you open a new issue and fill the template with the details to help us investigate more.
