### ISSUE TITLE
Problem with permission dialog

### ISSUE THREAD

**Issue by highthem** [Instabug/Instabug-Android#140] opened 2018-11-02 17:14 UTC
Hello,
At the initialisation of the instabug sdk, it ask for the write_external_storage permission.
I need this permission in my app but I don't want the dialog to be prompt automatically when it initialize.

I've tried to set my manifest like this

```<permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="remove" tools:selector="com.instabug.library"/>```

but it doesn't change anything.

Is there a variable to set on the builder or any solution to stop that?

**Comment by NourAbdelAal** [comment] 2018-11-02 20:50
Hello there 👋 

Nour from Instabug happiness team is here to help.

Could you please send the email you are using for Instabug through the support channel(contact us) so we can check this issue.

Thank you in advance 🙏

**Comment by Yahyaali1** [comment] 2018-11-17 07:50
I am facing a similar issue. 
Use Case:
As the splash screen appears in my app, I need to show user relevant permissions. However since insta bug is been initialized in the app component, as soon my dialog for seeking permission appear, they forcefully disappear followed by permission  required by insta bug. 
Is there a work around to this ?

**Comment by mzelzoghbi** [comment] 2019-01-28 09:13
@highthem @Yahyaali1 Thanks for reporting this.

We request the **WRITE_EXTERNAL_STORAGE**  when using Screenshot Invocation `InstabugInvocationEvent.SCREENSHOT`, so to workaround this, you can set invocation to `InstabugInvocationEvent.NONE` in the app class then you could change this in the runtime after your permission dialog using this API 
```
BugReporting.setInvocationEvents(InstabugInvocationEvent.SCREENSHOT);
```

And for disabling **intro**/**welcome** message you could use this API in the app class
```
Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED);
```
Then showing the welcome message in runtime by calling 

```
// for beta versions
Instabug.showWelcomeMessage(WelcomeMessage.State.BETA);
// for live versions
Instabug.showWelcomeMessage(WelcomeMessage.State.LIVE);
```
So, I'm closing this issue. Please feel free to reopen if you encounter this issue with the latest version **8.0.16**

Thank you! 😊

**Closed by mzelzoghbi** 2019-01-28 09:13 UTC

**Comment by douglasselph** [comment] 2019-10-18 18:38
I am using 8.7.0 and did the steps above (using NONE), yet the dialog is still appearing.

**Comment by mzelzoghbi** [comment] 2019-10-18 18:50
@douglasselph Can you provide which device model / os you are using and if it it reproducible on other devices, os versions or not ?

**Comment by mzelzoghbi** [comment] 2019-10-18 18:51
@douglasselph lets move this to https://github.com/Instabug/Instabug-Android/issues/243

Locking this issue.
